#!/bin/bash
# Save working state before compaction
# Auto-executed by PreCompact hook

set -euo pipefail

DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
HANDOFF="HANDOFF.md"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

cd "$REPO_ROOT"

# Capture git state
GIT_STATUS=$(git status --short 2>/dev/null || echo "No git repository")
GIT_DIFF_STAT=$(git diff --stat 2>/dev/null || echo "No uncommitted changes")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Try to extract current task from recent git log or uncommitted changes
CURRENT_TASK="Unknown"
if git log -1 --oneline 2>/dev/null | grep -oE "T-[0-9]+" >/dev/null 2>&1; then
    CURRENT_TASK=$(git log -1 --oneline | grep -oE "T-[0-9]+" | head -1)
elif echo "$GIT_DIFF_STAT" | grep -oE "T-[0-9]+" >/dev/null 2>&1; then
    CURRENT_TASK=$(echo "$GIT_DIFF_STAT" | grep -oE "T-[0-9]+" | head -1)
fi

# Get list of modified files
MODIFIED_FILES=""
if [ -n "$GIT_STATUS" ] && [ "$GIT_STATUS" != "No git repository" ]; then
    MODIFIED_FILES=$(echo "$GIT_STATUS" | awk '{print $2}' | head -10)
fi

# Generate HANDOFF.md
cat > "$HANDOFF" <<HANDOFF
# HANDOFF (Auto-saved: $DATE)

**Branch:** \`$GIT_BRANCH\`

## Current Task
**Likely Task:** $CURRENT_TASK (detected from git history)

*Check \`docs/todos.md\` to confirm priority*

## Uncommitted Changes
\`\`\`
$GIT_STATUS
\`\`\`

## Modified Files Summary
\`\`\`
$GIT_DIFF_STAT
\`\`\`

## Working Set (Files Changed)
$(if [ -n "$MODIFIED_FILES" ]; then
    echo "$MODIFIED_FILES" | while read -r file; do
        echo "- \`$file\`"
    done
else
    echo "No uncommitted changes"
fi)

## Next Steps
1. If changes uncommitted: Review and commit with \`/finish\`
2. Run \`/context-refresh\` to reload project context
3. Check \`docs/todos.md\` for next priority task
4. Read relevant files from working set above

---

*Auto-generated by \`.claude/hooks/save-handoff.sh\` on $DATE*
HANDOFF

echo "✅ HANDOFF.md saved to $REPO_ROOT/HANDOFF.md"

# Verify file was created and is not empty
if [ ! -f "$HANDOFF" ]; then
    echo "❌ ERROR: HANDOFF.md was not created!" >&2
    exit 1
fi

if [ ! -s "$HANDOFF" ]; then
    echo "❌ ERROR: HANDOFF.md is empty!" >&2
    exit 1
fi

# Verify minimum content (should have at least the header)
if ! grep -q "# HANDOFF" "$HANDOFF"; then
    echo "❌ ERROR: HANDOFF.md has invalid content!" >&2
    exit 1
fi

echo "✅ Validation passed: HANDOFF.md is valid"
exit 0
