#!/bin/bash
# Save working state before compaction
# Auto-executed by PreCompact hook

set -euo pipefail

DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
HANDOFF="HANDOFF.md"

# ── Guard: must be inside a git repository ──────────────────────────────────
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "⚠️  save-handoff.sh: Not inside a git repository. Skipping HANDOFF save." >&2
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ── Guard: handle detached HEAD gracefully ───────────────────────────────────
GIT_BRANCH=$(git branch --show-current 2>/dev/null || true)
if [[ -z "$GIT_BRANCH" ]]; then
  GIT_BRANCH="(detached HEAD: $(git rev-parse --short HEAD 2>/dev/null || echo 'unknown'))"
fi

# Capture git state
GIT_STATUS=$(git status --short 2>/dev/null || echo "")
GIT_DIFF_STAT=$(git diff --stat 2>/dev/null || echo "")

# Try to extract current task from recent git log or uncommitted changes
CURRENT_TASK="Unknown"
if git log -1 --oneline 2>/dev/null | grep -oE "T-[0-9]+" >/dev/null 2>&1; then
    CURRENT_TASK=$(git log -1 --oneline | grep -oE "T-[0-9]+" | head -1)
elif echo "$GIT_DIFF_STAT" | grep -oE "T-[0-9]+" >/dev/null 2>&1; then
    CURRENT_TASK=$(echo "$GIT_DIFF_STAT" | grep -oE "T-[0-9]+" | head -1)
fi

# Get list of modified files
MODIFIED_FILES=""
if [[ -n "$GIT_STATUS" ]]; then
    MODIFIED_FILES=$(echo "$GIT_STATUS" | awk '{print $2}' | head -10)
fi

# ── Write HANDOFF.md ─────────────────────────────────────────────────────────
if ! cat > "$HANDOFF" <<HANDOFF
# HANDOFF (Auto-saved: $DATE)

**Branch:** \`$GIT_BRANCH\`

## Current Task
**Likely Task:** $CURRENT_TASK (detected from git history)

*Check \`docs/todos.md\` to confirm priority*

## Uncommitted Changes
\`\`\`
${GIT_STATUS:-No uncommitted changes}
\`\`\`

## Modified Files Summary
\`\`\`
${GIT_DIFF_STAT:-No uncommitted changes}
\`\`\`

## Working Set (Files Changed)
$(if [ -n "$MODIFIED_FILES" ]; then
    echo "$MODIFIED_FILES" | while read -r file; do
        echo "- \`$file\`"
    done
else
    echo "No uncommitted changes"
fi)

## Next Steps
1. If changes uncommitted: Review and commit with \`/finish\`
2. Run \`/context-refresh\` to reload project context
3. Check \`docs/todos.md\` for next priority task
4. Read relevant files from working set above

---

*Auto-generated by \`.claude/hooks/save-handoff.sh\` on $DATE*
HANDOFF
then
  echo "❌ ERROR: Failed to write HANDOFF.md" >&2
  exit 1
fi

# ── Validate output ──────────────────────────────────────────────────────────
if [[ ! -f "$HANDOFF" ]]; then
  echo "❌ ERROR: HANDOFF.md was not created!" >&2
  exit 1
fi

if [[ ! -s "$HANDOFF" ]]; then
  echo "❌ ERROR: HANDOFF.md is empty!" >&2
  exit 1
fi

if ! grep -q "# HANDOFF" "$HANDOFF"; then
  echo "❌ ERROR: HANDOFF.md has invalid content!" >&2
  exit 1
fi

echo "✅ HANDOFF.md saved to $REPO_ROOT/HANDOFF.md"
echo "✅ Validation passed: HANDOFF.md is valid"
exit 0
